### ISSUE TITLE
communication

### ISSUE THREAD

**Issue by scatterp2** [SaladDais/Hippolyzer#35]
hi i would like to reach you in world or on discord to discuss some ideas for this tool where could i find you?

**Comment by SaladDais** [comment]
Hi there, thanks for reaching out! I prefer long-form communication for technical discussions.

The best way to get ahold of me for ideas / issues related to Hippolyzer is either through Issues or Discussions on this repo. Ideas would probably go best under the Discussions tab, since I get notifications for all new postings. Ideally I would like most discussion for Hippolyzer to take place in the open due to its intended use as a reference implementation.

Failing that, I can also be reached by email through the email address listed in my Github profile.
